name: Deploy Website

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3-beta
        with:
          node-version: 16
      
      - name: Github Action for yarn
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command

      - name: Build
        run: yarn build

      - name: installing to surge
        run: npm install -g surge

      - name: Deploy to surge
        run: surge ./build http://baberx.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}

          
